### ISSUE TITLE
Addition to Ledger Manager

### ISSUE THREAD

**Issue by yura-pakhuchiy** [parkerhoyes/bolos-app-seedutility#1]
In [this](https://www.reddit.com/r/ledgerwallet/comments/6ez4qs/ledger_nano_s_seed_utility_app_released/dierode/) thread ledger developer offered to add seed utility to ledger manager. However it never happened. I wonder why? Any technical issues?

**Comment by parkerhoyes** [comment]
I am not aware of any such technical issues.

In the near future installing 3rd party apps will be a much more steamlined process that's easier for end users (so they won't have to mess with the command line and whatnot), so adding apps to the Ledger Manager won't be as much of a necessity. Perhaps @btchip could shed some light on whether or not he'd like this app added to the manager in the meantime.

**Comment by yura-pakhuchiy** [comment]
I think main concern here is audit, not easy of installation, due to nature of the device and purpose of the program. Sources are available, but auditing them is not a trivial task, which requires time and familiarizing self with BOLOS platform. If Ledger will sign binary and add to the manager, it means they probably audited it, so it is safe to use for users without additional audit.

**Comment by parkerhoyes** [comment]
I can confirm that this app will be added to the official Ledger Manager soon.

**Comment by yura-pakhuchiy** [comment]
@parkerhoyes It is a great news, thank you!
