### ISSUE TITLE
Addition of a Shamir's Secret Sharing feature

### ISSUE THREAD

**Issue by aido** [parkerhoyes/bolos-app-seedutility#2]
Hi,

Are there any plans to add a Shamir's Secret Sharing feature to this app? e,g, an implementation of Blockchain Commons' Sharded Secret Key Reconstruction [(SSKR)](https://github.com/BlockchainCommons/bc-sskr) as described in [BCR-0011](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-011-sskr.md).

**Comment by parkerhoyes** [comment]
@aido sorry, but I don't actively work on these apps anymore. If you're interested in working on it yourself, I'd be happy to review a PR.
